### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by facontidavide** [pal-robotics/pal_statistics#5]
Hi,

the LGPL license is very limiting for a library like pal_statistics.

Since this library is supposed to be used in pretty much all the nodes of the system that the user wants to monitor, we are reasonably concerned by the viral nature of this license.

Would you consider changing it to MIT or BSD?

**Comment by v-lopez** [comment]
Yeah, I think that shouldn't be an issue.

I'll get back on this in a few days.

**Comment by veimox** [comment]
@v-lopez  Thanks for that! You forgot to remove the GPL license from the header files :smile:

**Comment by v-lopez** [comment]
Thanks @veimox, you are right.

I have fixed it, tonight it will be synchronized.
