### ISSUE TITLE
Update docker readme

### ISSUE THREAD

**Issue by aremazeilles** [pal-robotics/pal_statistics#6]
Following the [tutorial indications](http://wiki.ros.org/pal_statistics/Tutorials/Aggregate%2C%20store%20and%20visualise%20statistics), where the first action suggested is to build and run the graphite - grafana server.

 I started with the interactive mode, but I could not see my variable in the grafana dashboard.
I then used the last command indicated, and this time it worked. 
Could it be because more ports are redirected (2003 and 2004)?

I made a try of the interactive launch, adding these 2 additional redirections, and it works.

It might be useful to indicate to what refers each port.

**Comment by v-lopez** [comment]
Thanks for the report, readme updated. 

Feel free to close the issue if you think there's enough information there now.

**Comment by aremazeilles** [comment]
Just perfect, thanks!
