### ISSUE TITLE
Extend metric and function description

### ISSUE THREAD

**Issue by aremazeilles** [pal-robotics/pal_statistics#7]
This is related to the wiki tutorial [Aggregate, store and visualise statistics](http://wiki.ros.org/pal_statistics/Tutorials/Aggregate%2C%20store%20and%20visualise%20statistics). If you prefer me to bring that issue to ros.answers, just tell me.

The tutorial states that:

> There are two types of metrics: timers (t) and gauges (g). Timers will give you a summary of the aggregated data (count, lower, upper and average) while gauge will show the last value logged.

 `statsdcc` seems to handle 4 metric types: timers, gauges, counter, and set. When trying to add a set metric, I got a segmentation fault when launching  `statsdcc`. I did it with a simple publication of an increasing value. I don't know if this can be the cause of the prb.

Then it is unclear how / where the functions associated to each metric are defined (who is defining them)?

What I could see is that:

* timer as lower, mean, upper, count.
  * The count is unclear to me although. Is it the number of publication since the first publication?
* Counter as count and rate. Is rate the rate of publication?
* Gauge seems to only be a value, the latest value recorded as stated in the tutorial. 

It could be nice providing for each metric a light description of the functions associated to it

**Comment by v-lopez** [comment]
Hi @aremazeilles,

Could you share the code or configuration files that make it crash? We'll try to look into it this week.

**Comment by aremazeilles** [comment]
I made a simple trial changing the default topics.yaml file which is loaded using the command `rosparam load topics.yaml statsdcc_node`:

```yaml
topics:
    - name: '/my_statistics_topic'
      stats:
          - name: 'my_var'
            type: ['s']
```
But I  don't know if it expects the data published to be something special

**Comment by v-lopez** [comment]
The problem with sets is that is that it expects the data to be strings. We only deal with floating point value, so counting floats can be finnicky.

Nevertheless I've pushed a fix, I believe it should handle sets properly now.
