### ISSUE TITLE
frame_id in Statistics.msg

### ISSUE THREAD

**Issue by asherikov** [pal-robotics/pal_statistics#8]
Hi, do you use `frame_id` for anything? I am thinking about using it to store a common name prefix for all measurements and adding this feature to plotjuggler.

**Comment by v-lopez** [comment]
It's not used, only the stamp. But keep in mind that statistics are already grouped under topic name, do you need further grouping?

**Comment by asherikov** [comment]
Ok, thanks.
I have my own framework for statistics collection where messages from multiple sources are published on the same topic. The problem is that I don't want to implement plotjuggler plugin to support my custom messages, but it should be possible to reuse yours.
