### ISSUE TITLE
Binary Release Foxy

### ISSUE THREAD

**Issue by facontidavide** [pal-robotics/pal_statistics#9]
Hi,

would it be possible to release at least the packages **pal_statistics** and **pal_statistics_msgs** for foxy.

I would love to add that to Plotjuggler, but I am unable to do that unless **pal_statistics_msgs** isn't released

**Comment by v-lopez** [comment]
Requested https://github.com/ros/rosdistro/pull/30996 and https://github.com/ros/rosdistro/pull/30997

**Comment by jacobperron** [comment]
Currently, the the build is failing https://build.ros2.org/job/Fbin_uF64__pal_statistics_msgs__ubuntu_focal_amd64__binary/39/:

```
23:05:20 CMake Error at /opt/ros/foxy/share/rosidl_generator_c/cmake/rosidl_generator_c_generate_interfaces.cmake:168 (find_package):
23:05:20   By not providing "Findament_cmake_cppcheck.cmake" in CMAKE_MODULE_PATH this
23:05:20   project has asked CMake to find a package configuration file provided by
23:05:20   "ament_cmake_cppcheck", but CMake did not find one.
23:05:20 
23:05:20   Could not find a package configuration file provided by
23:05:20   "ament_cmake_cppcheck" with any of the following names:
23:05:20 
23:05:20     ament_cmake_cppcheckConfig.cmake
23:05:20     ament_cmake_cppcheck-config.cmake
```

I think this could be resolved by removing the linter tests here:

https://github.com/pal-robotics/pal_statistics/blob/69b11f241b61b2de8437a3d8c9e171489ba7e998/pal_statistics_msgs/CMakeLists.txt#L22

**or**, you could try declaring a test dependency in the package.xml to `<test_depend>ament_lint_common</test_depend>` (just a guess).

**Comment by Noel215** [comment]
I've requested the releases for foxy [#34322](https://github.com/ros/rosdistro/pull/34322) galactic [#34318](https://github.com/ros/rosdistro/pull/34318) and humble [#34321](https://github.com/ros/rosdistro/pull/34321)

Update: All have been merged
